### PR TITLE
AC-131 fix log rotation

### PR DESCRIPTION
**Pull request by nlgordon**

### CODE REVIEW

**Comment by Slair1** [comment]
@nlgordon Hi Nate, do you know if this is fixed in upstream?  Just wondering if we should cherry-pick any upstream commits to fix this vs. doing our own fix?

**Comment by nlgordon** [comment]
@Slair1 Upstream hasn't changed their logging to a version that would support this capability. They did change their logging dependency to a maintained library that is fixing security vulnerabilities, but they are still sitting on the 1.2.x version of log4j as a whole. So unfortunately there isn't anything to cherry-pick that I can see.

It should also be noted that this change will require manually merging in changes to the log4j-cloud.xml files on the hosts and agents since RPM won't overwrite those config files if they have been touched.

**Comment by Slair1** [comment]
> @Slair1 Upstream hasn't changed their logging to a version that would support this capability. They did change their logging dependency to a maintained library that is fixing security vulnerabilities, but they are still sitting on the 1.2.x version of log4j as a whole. So unfortunately there isn't anything to cherry-pick that I can see.
> 
> It should also be noted that this change will require manually merging in changes to the log4j-cloud.xml files on the hosts and agents since RPM won't overwrite those config files if they have been touched.

Thanks @nlgordon - could you provide documentation in this PR or the JIRA Issue on how we should modify the xml files?

**Comment by nlgordon** [comment]
@Slair1 I looked at the prod mgmt servers and the change to the log config xml files will be the same as the changes I made to the client log4j-cloud.xml.in file in this PR. Lines 33 and 45 need to be changed to use the class `org.apache.cloudstack.utils.logging.LimitedTimeBasedRollingPolicy` and add the param `<param name="maxBackups" value="730"/>` to the rollingPolicy element. If desired, the rotation limits can be applied to the agent log files with the same changes to their log4j config files.

Additionally, the access log rotation is enabled by adding `yyyy_mm_dd` to the file path in server.properties. In this PR I did it like this: `access.log=/var/log/cloudstack/management/access.yyyy_mm_dd.log`. It will likely also need to be manually applied.

One other change on the hosts is fixing permissions for the logrotate cloudstack-agent file. RPM should fix it, but it would be wise to verify that it is actually 644.

**Review by bharkarampudi — APPROVED** [review]

**Pull request merged**
