### PR TITLE
AC-138 Require SSO Login

### PR DESCRIPTION
**Pull request by nlgordon**

### CODE REVIEW

**Comment by Slair1** [comment]
It sounds like the team is rolling out this week the ability to manage users from MyAdaptiveCloud.  So if that is the case, we don't need as much done on this PR.  On this PR I say we leave the Add User UI the same... BUT we remove the Add User button entirely from the UI unless the logged in user is a Root Admin.  Is that possible?

On the Login Page, could we hide these two fields unless the special query param is passed?
image

**Comment by ggoodrich-ipp** [comment]
On the issue of 'remove the Add User button entirely unless it is a Root Admin', could we just take the permission away from Domain Admin to accomplish this? Our MYAC Api uses a Root Admin key, and thus we would still be able to manage from MYAC.

**Comment by nlgordon** [comment]
I tested the idea of removing the permission from domain admin. Unfortunately I think some things are checking 'is Root Admin' or 'is Domain Admin' directly and not checking role permissions. The UI doesn't actually get rid of the button, but just logs you out when you try to create an account with a 'Session Expired' error. Not a great user experience. Otherwise, removing it from the UI and API in code will be pretty simple.

On a related note, does any of this impact the white label customers? I'm just unsure of how they interact with our environment with their users.

**Comment by nlgordon** [comment]
@Slair1 I've got those changes in and deployed to lab. @ggoodrich-ipp Removing the permissions from domain admins didn't make the UI do the right thing, but it did keep someone from using the APIs directly. So I would recommend both deploying this change and updating the role permissions.

**Comment by nlgordon** [comment]
I've been doing some additional testing of this and realized that domain admins can still create sub-domains. But not accounts in those domains. Do we want to prevent them from creating sub-domains as well? I could see that being somewhat confusing for users. Since they can't create accounts in those sub-domains, they wouldn't be able to create any resources in that sub-domain.

**Comment by nlgordon** [comment]
SQL Statement to remove the relevant permissions from domain admins: 
`update role_permissions rp, roles r set permission = 'DENY' where rp.rule IN ('createAccount', 'createUser', 'authorizeSamlSso', 'deleteAccount', 'deleteUser', 'disableAccount', 'enableAccount', 'lockAccount') and rp.role_id = r.id and r.name = 'Domain Admin';`

I've tested this in lab, and from what I can tell (without running it) it will work identically in prod.

**Comment by Slair1** [comment]
@nlgordon Yea, i think we should remove the creation of Domains also.  I think we should also remove Change Password and Delete User for non-RootAdmins:

image

**Comment by nlgordon** [comment]
I've got those changes done and deployed to Lab. Let me know if there is anything else you see.

**Comment by Slair1** [comment]
Hi @nlgordon sorry one more change we might as well remove the Disable User action too for non-root admins.

Noticing one strange thing also.  When a normal User logs in and view the Quick View, it now comes back blank.

image

**Comment by nlgordon** [comment]
@Slair1 I've removed user disable/enable and account disable/enable from domain admins. I also tracked down the user quickview issue to an existing bug where it wouldn't correctly load. I've included a fix for that in this PR. Changes are up in Lab now.

**Comment by Slair1** [comment]
It looks like if the user logs out, the user is immediately logged back in.  Is there a way to reproduce the current production logout functionality where it displays this?

image

**Comment by nlgordon** [comment]
@Slair1 I've updated the PR to have the logged out page show. Minus the login form. If the user manually refreshes the page, it will log them in again. Or if they just go to the page again. Given how the SAML process works, I'm not sure I've got a great way to prevent that from happening. It appears that the ACS logout doesn't trigger a logout on the SSO side. I checked and prod operates the same way.

**Comment by Slair1** [comment]
@nlgordon This looks good to me! Yes, correct, we didn't want to log them out of SSO incase they were logged into other services also.  I assume you're happy with this and it's good to merge?

**Review by Slair1 — APPROVED** [review]

**Comment by nlgordon** [comment]
@Slair1 I'm good with it!

**Pull request merged**
